
# SentinelHub API identifier: https://docs.sentinel-hub.com/api/latest/user-guides/beginners-guide/
api_id: ${oc.env:SENTINELHUB_API_ID}

# SentinelHub API secret: https://docs.sentinel-hub.com/api/latest/user-guides/beginners-guide/
api_secret: ${oc.env:SENTINELHUB_API_SECRET}

#  Name of imagery (javascript), e.g.
evalscript_name: "ndvi_evalscript"