# SentinelHub API identifier: https://docs.sentinel-hub.com/api/latest/user-guides/beginners-guide/
api_id: ${oc.env:SENTINELHUB_API_ID}

# SentinelHub API secret: https://docs.sentinel-hub.com/api/latest/user-guides/beginners-guide/
api_secret: ${oc.env:SENTINELHUB_API_SECRET}

#  Name of index and imagery evalscript (v3)
index_name:
  ndvi:
    evalscript_name: "ndvi_evalscript"

# Name of remote sensing data source, e.g. sentinel_hub, planet
imagery_source: "sentinel_hub"